version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    restart: always
  app:
    image: openjdk:19
    command: /app/mvnw spring-boot:run
    ports:
      - '8080:8080'
    working_dir: '/app'
    volumes:
      - ./:/app
volumes:
  db:
    driver:
      local